### PR TITLE
feat: Add new MineType `All` which corresponds to '*'

### LINKED ISSUE #74: Mime type
Hi,

It is possible in ngx-upload to accept all types of files.

Thanks

### PR DESCRIPTION
**Pull request by wKoza**
closes #74

### CODE REVIEW

**Comment by ghten** [comment]
Hi,

I have put 

public optionsInput: InputFileOptions = {
    multiple: true,
    accept: [MineTypeEnum.All],
  };

and I have this error over all files
this file is not accepted because of its type 

Thanks

**Comment by wKoza** [comment]
Hi @ghten ,

Are you sure that you have the last version 8.1.0 in your node_modules. I tested this option in my test application and it's work well.

**Comment by ghten** [comment]
Yes the version is "@wkoza/ngx-upload": "^8.1.0",

**Comment by wKoza** [comment]
I will push the new version of my test application tonight. Keep in touch.

**Comment by wKoza** [comment]
The new version is online : https://ngx-upload.github.io/#/simple-bootstrap

this is the repository : https://github.com/wKoza/ngx-uploader-app

I use the new MineType with the input button (section bootstrap).

it seems good.

**Comment by ghten** [comment]
Hi,

It's not bootstrap, it's material

**Comment by ghten** [comment]
Hi,

In bootstrap in your example https://ngx-upload.github.io/#/simple-bootstrap is the same error

error during drop action:  
{…}
​errorAccept: true
​errorMultiple: false
​item: File
​​lastModified: 1565682650710
​​name: "countries.sql"
​​size: 18581
​​type: ""
​​webkitRelativePath: ""

Thanks

**Comment by wKoza** [comment]
Hi @ghten ,
Sorry, I'm a little buzzy now.
Thank for your report, I'll see that as soon as possible.
keep in touch

**Comment by wKoza** [comment]
Hi @ghten ,
It should be OK with the 8.1.1

**Comment by ghten** [comment]
Thanks wKoza. I've done tests and it seems that everything is working

**Pull request merged**
